datadog:
  apiKeyExistingSecret: "datadog-secret"
  appKeyExistingSecret: "datadog-secret"
  dogstatsdOriginDetection: true
  nonLocalTraffic: true
  collectEvents: true
  leaderElection: false
  leaderLeaseDuration: 60
  logsEnabled: true # We use another log collector
  logsConfigContainerCollectAll: true
  apmEnabled: true
  processAgentEnabled: true
  logs:
    containerCollectAll: true
    containerCollectUsingFiles: true
  daemonset:
    containers:
      agent:
        resources: {} # configure
      processAgent:
        resources: {} # configure
      traceAgent:
        resources: {} # configure
    useHostPort: true
    priorityClassName: system-node-critical
  volumes:
    - name: empty-dir
      emptyDir: {}
  volumeMounts:
    - name: empty-dir
      mountPath: /etc/datadog-agent/conf.d/kubernetes_state.d
      readOnly: true
    - name: empty-dir2
      mountPath: /etc/datadog-agent/conf.d/vault.d
      readOnly: true
  confd:
    vault.yaml: |-
      ad_identifiers:
        - vault
      init_config:
      instances:
        - api_url: http://%%host%%:8200/v1
          detect_leader: true
          tls_verify: false
          no_token: true
      logs:
        - type: file
          path: /vault/vault-audit.log
          source: vault
          service: vault-gke
    kubernetes_state.yaml: |-
      ad_identifiers:
        - kube-state-metrics
      init_config:
      instances:
        - kube_state_url: http://%%host%%:8080/metrics
          telemetry: true
  resources: {} # configure
clusterAgent:
  enabled: true
  replicas: 2
  clusterChecks:
    enabled: true
  env:
    - name: DD_CLUSTER_CHECKS_EXTRA_TAGS
      value: "kubernetescluster:vault-helm"
  priorityClassName: system-cluster-critical
  resources: {} # configure
  livenessProbe:
    httpGet:
      port: 5000
      path: /metrics
      scheme: HTTP
  readinessProbe:
    httpGet:
      port: 5000
      path: /metrics
      scheme: HTTP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  