---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "datadog-vault-config-map"
  namespace: andrew-vault
  annotations:
    ad.datadoghq.com/service.check_names: '["vault"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: |
      [
      {
          "api_url": "https://%%host%%:8200/v1",            
          "detect_leader": "true",            
          "tls_verify": "false"
      }
      ]