name: Tests

on: [push, workflow_dispatch]

jobs:
  bats-unit-tests:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-test-tools
      - run: bats --tap --timing ./test/unit
=======
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup-test-tools
      - run: bats ./test/unit -t
>>>>>>> 7f26aa5 (Datago 30304/upgrading vault to 1.9.2 (#14))

  chart-verifier:
    runs-on: ubuntu-latest
    env:
      CHART_VERIFIER_VERSION: '1.2.1'
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
      - name: Setup test tools
        uses: ./.github/workflows/setup-test-tools
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
      - run: go install github.com/redhat-certification/chart-verifier@${CHART_VERIFIER_VERSION}
      - run: bats --tap --timing ./test/chart
=======
      - uses: actions/checkout@v2
      - name: Setup test tools
        uses: ./.github/workflows/setup-test-tools
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.4'
      - run: go install github.com/redhat-certification/chart-verifier@${CHART_VERIFIER_VERSION}
      - run: bats ./test/chart -t
>>>>>>> 7f26aa5 (Datago 30304/upgrading vault to 1.9.2 (#14))
